---
title: "ProgressReport"
author: "Liz Muntean"
date: "11/16/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
November 22, 2020

As the lead author never got back to me I started working on the code myself. I was able to construct a data frame from the data plotting half of the points (only the least-squares adjusted mean points) and plot it in a similar manner to how the authors constructed Figure 3 in their paper. Plotting the other half of the points (the arithmetic mean with standard error bars) will take more manipulation of the data and the creation of another data frame in order for those points to be included in the figure as well. My x-axis is not quite in the same order as the authors but ranking the values from highest to lowest was the closest way I could get to having my graph look like theirs. 

November 16, 2020

Working to convert excel tables into csv. Some trouble with the headers and the formatting, need to be sorted out manually.

email to corresponding author:

Hello Dr. Klironomos,

I very much enjoyed your 2017 paper in New Phytologist, Evolutionary asymmetry in the arbuscular mycorrhizal symbiosis, conservatism in fungal morphology does not predict host plant growth. I am currently a Master's student at Tulane University in Louisiana participating in a Data and Software class for biologists learning how to code and reproduce the results from scientific papers. The figures in your paper are compelling to me and I believe learning how to create them would be very useful for my research. I am particularly interest in reproducing Figure 2. Is there any chance you would be able to share the code you used to make the figure? I would be beyond grateful. Thank you so much for your time!

Sincerely,

Liz Muntean